export const PRODUCT_LIST_REQUEST: string = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS: string = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL: string = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST: string = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS: string = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL: string = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQUEST: string = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS: string = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL: string = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_CREATE_REQUEST: string = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS: string = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL: string = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET: string = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST: string = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS: string = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL: string = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET: string = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_CREATE_REVIEW_REQUEST: string =
  'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS: string =
  'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL: string = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET: string =
  'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_TOP_REQUEST: string = 'PRODUCT_TOP_REQUEST';
export const PRODUCT_TOP_SUCCESS: string = 'PRODUCT_TOP_SUCCESS';
export const PRODUCT_TOP_FAIL: string = 'PRODUCT_TOP_FAIL';
